### ISSUE TITLE
A cap of legend in fill scale

### ISSUE THREAD

**Issue by JJiaSu** [teunbrand/gguidance#2] opened 2023-07-24 13:24 UTC
Hi, I am trying to use this **guide_colourbar_cap** function, but I cannot find a way to use it in the fill scale, guides(fill = guide_colourbar_cap()) does not work. Could you please share an example, thank you.

**Comment by teunbrand** [comment] 2023-07-24 16:37
Works as intended on my end. What R/ggplot2 versions are you using?

``` r
library(gguidance)
#> Loading required package: ggplot2

ggplot(mtcars, aes(disp, mpg, fill = drat)) +
  geom_point(shape = 21) +
  guides(fill = guide_colourbar_cap())
```

![](https://i.imgur.com/ftmj7Gq.png)

<sup>Created on 2023-07-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by JJiaSu** [comment] 2023-07-25 11:53
Thanks for your response and sharing, Really nice works! But it can not work in my coding, my ggplot version is 3.4.2, and R is 4.2.1, I am not sure what happened, my figure look like this, 
`ggplot(subset(bar.continent1), aes(as.numeric(WMO_zone), 
                                   as.numeric(rank), fill = percent_126)) +
  geom_point(shape = 21) +
  guides(fill = gguidance::guide_colourbar_cap())`
![image](https://github.com/teunbrand/gguidance/assets/70686317/2f73f49a-6ccb-4c35-bcca-f02fa04730e1)

**Comment by teunbrand** [comment] 2023-07-25 13:46
If you're using the latest CRAN version of ggplot2, this package will not work at all. It is designed to work with the current development version of ggplot2 where guides have had a makeover that made them more extendible, without which I couldn't make these guide extensions.

**Comment by teunbrand** [comment] 2024-04-27 08:07
Closing this as the current main branch should work with CRAN version of ggplot2 now

**Closed by teunbrand** 2024-04-27 08:07 UTC
